#!/usr/bin/env bash
#  Bash script that configures a new Ubuntu machine to HAproxy
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*
echo "frontend load-banlancer
    bind *:80
    mode http
    default_backend web-backend" | sudo tee /etc/haproxy/haproxy.cfg
echo "backend web-backend
    balance roundrobin
    server 3127-web-01 35.231.241.237:80 check
    server 3127-web-02 34.237.200.98:80 check" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart